openapi: 3.0.3
components:
  schemas:
    CreateCustomIncomeRequest:
      description: A transport object that carries the details for creating a new fixed income.
      type: object
      allOf:
        - $ref: '../../../schemas/income/custom/base-custom-income.yaml'