openapi: 3.0.3
components:
  schemas:
    BaseFixedIncome:
      description: A transport object that represents an income.
      type: object
      properties:
        incomeName:
          type: string
        incomeType:
          type: string
          $ref: '../../shared/income-type.yaml#/components/schemas/IncomeType'
        incomeOccurrence:
          $ref: '../../shared/occurrence.yaml#/components/schemas/Occurrence'
        specifiedOccurrences:
          type: array
          items:
            $ref: '../../shared/specified-occurrence.yaml#/components/schemas/SpecifiedOccurrence'