spring:
  application:
    name: SampleTracker
  datasource:
    url: jdbc:postgresql://localhost:5432/sample-tracker
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  servlet:
    context-path: /sample-tracker
