openapi: 3.0.3
components:
  schemas:
    CreateFixedIncomeResponse:
      description: A transport object that carries the details for a newly created fixed income.
      type: object
      allOf:
        - $ref: '../../../schemas/income/fixed/base-fixed-income.yaml'