openapi: 3.0.3
components:
  schemas:
    CreateFixedIncomeRequest:
      description: A transport object that carries the details for creating a new fixed income.
      type: object
      allOf:
        - $ref: '../../../schemas/income/fixed/base-fixed-income.yaml'